### ISSUE TITLE
Regridding Prototype

### ISSUE THREAD

**Issue by sol1105** [roocs/clisops#68]
## Tasks on the way to a regridding prototype
- [x] Review this list after 1st October and 2nd October Meetings
- [x] Set up repo: https://github.com/roocs/regrid-prototype

### Working Jupyter Notebook Examples to regrid (and visualize) ...
- [x] Regular lat-lon grid: https://github.com/roocs/regrid-prototype/blob/main/docs/notebooks/xESMF_Test.ipynb
- [x] Curvilinear grid
- [x] Tripolar curvilinear grid (eg. NEMO, MPIOM)
- [x] Unstructured grid (eg. FESOM ocean submodel of AWI-ESM, CMIP6 tos)

### Familiarize with clisops, daops, dachar and roocs-utils
- [x] Basics
- [ ] On the fly / learning by doing

### Identify / Extend / Create functions to ...
Read standardized model output into xarray  DataSets (from disk, also via intake-esm?) -> Not required, assume data has been read into an xarray dataset
- [x] Write computed output to disk
Inspect / Identify / Fix the input grids -> Not required for the prototype
- [x] Select / Read the output grid
- [x] Create / Reuse regridding weights
- [x] Regridding
- [x] Basic error handling
- [x] Basic Handling of masks
- [x] Basic preparation of grids / bounds for xESMF
- [x] Advanced preparation of grids / bounds for xESMF (curvilinear and less complex ocean grids)
- [x] Advanced/Specific handling of masks
- [x] Wrapper / Object for above code / functions.

### Tests
- [x] Add testdata to the mini-esgf-data repo
- [x] Set up basic tests

### Collect information
- [x] Identify the grid type
- [ ] Supported standards regarding grid description
- [ ] Progress the literature review

### Set up external tools for comparison 
- [ ] NCO
- [ ] CDO
- [ ] YAC
- [ ] (ESMValTool/Iris)
- [ ] (others)

**Comment by sol1105** [comment]
This can serve as a starting point for discussion of the design:

![Regrid_prototype](https://user-images.githubusercontent.com/10836031/109781296-14792b80-7c08-11eb-948b-24f4a464c2f4.png)

**Comment by sol1105** [comment]
Update after a first discussion

![Regrid_prototype_Day1](https://user-images.githubusercontent.com/10836031/109846655-b1f74e00-7c4e-11eb-9025-a9af54b9b81a.png)
